apiVersion: v2
name: damap-chart
description: A tool to create machine-actionable data management plans.
type: application

version: 0.1.0-rc.1
appVersion: "5.0.0-rc.1"

kubeVersion: ">=1.25.0"

home: https://damap.org
sources:
  - https://github.com/damap-org/damap-backend
  - https://github.com/damap-org/damap-frontend

keywords:
  - damap
  - data-management
  - dmp
  - research
  - pure
  - keycloak
  - oidc
  - openid

maintainers:
  - name: DAMAP Team
    email: info@damap.org

icon: https://damap.org/logo.svg

annotations:
  artifacthub.io/prerelease: "true"
  artifacthub.io/changes: |
    - Release candidate 1 for the DAMAP Helm chart version 0.1.0
