apiVersion: v2
name: damap-chart
description: A tool to create machine-actionable data management plans.
type: application

version: 0.2.1
appVersion: "5.0.1"

kubeVersion: ">=1.25.0"

home: https://damap.org
sources:
  - https://github.com/damap-org/damap-backend
  - https://github.com/damap-org/damap-frontend
  - https://github.com/damap-org/damap-chart

keywords:
  - damap
  - data-management
  - dmp
  - research
  - pure
  - keycloak
  - oidc
  - openid

maintainers:
  - name: DAMAP Team
    email: info@damap.org

icon: https://damap.org/logo.svg

annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump DAMAP frontend to 5.0.1
    - kind: changed
      description: Bump Keycloak to 26.4

    - kind: fixed
      description: Prevent PostgreSQL collation version mismatches for newly created databases
