{{- if .Values.openshift }}

{{- if ne .Values.customBuild.backend.name "" }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.customBuild.backend.name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.customBuild.backend.name }}
spec:
  source:
    type: Git
    git:
      uri: "{{ .Values.customBuild.backend.repo }}"
      ref: "{{ .Values.customBuild.backend.ref }}"
    contextDir: /
  strategy:
    type: docker
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Values.customBuild.backend.name }}:{{ .Values.customBuild.backend.ref }}"
  resources:
    limits:
      memory: 2G
    requests:
      cpu: 10m
      memory: 512Mi
  triggers:
    - type: ConfigChange
{{- end }}

{{- if ne .Values.customBuild.frontend.name "" }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.customBuild.frontend.name }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.customBuild.frontend.name }}
  namespace: {{ .Release.Namespace }}
spec:
  source:
    type: Git
    git:
      uri: "{{ .Values.customBuild.frontend.repo }}"
      ref: "{{ .Values.customBuild.frontend.ref }}"
  strategy:
    type: Docker
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Values.customBuild.frontend.name }}:{{ .Values.customBuild.frontend.ref }}"
  resources:
    limits:
      memory: 2G
    requests:
      cpu: 10m
      memory: 512Mi
  triggers:
    - type: ConfigChange
{{- end }}

{{- end }}
