{{- if .Values.frontend.customize }}
---
apiVersion: v1
kind: Secret
metadata:
  name: damap-customization
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: damap-customization
stringData:
  logo.svg: {{ .Values.frontend.logo | quote }}
  logo-cropped.svg: {{ .Values.frontend.logoCropped | quote }}
{{- end }}
