{{- if .Values.pure.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: damap-pure
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: damap-pure
stringData:
  persons.json: {{ .Values.pure.personsData | toJson | quote }}
  projects.json: {{ .Values.pure.projectsData | toJson | quote }}
{{- end }}
