{{- if .Values.keycloak.deploy }}
{{- if .Values.keycloak.persistData }}
{{- if not .Values.openshift }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-db
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: "{{ .Values.keycloak.storageClassName }}"
  claimRef:
    namespace: "{{ .Release.Namespace }}"
    name: keycloak-db
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: {{ .Values.keycloak.hostFolder }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  storageClassName: "{{ .Values.keycloak.storageClassName }}"
  volumeMode: Filesystem
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: keycloak
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      volumes:
        - name: keycloak
          secret:
            secretName: keycloak
        - name: damap-realm
          secret:
            secretName: damap-realm
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.3
          resources:
            requests:
              cpu: 10m
              memory: 512Mi
            limits:
              cpu: "0.5"
              memory: 2G
          args:
            - start
            - --http-enabled=true
            - --proxy-headers
            - forwarded
            - --import-realm
          env:
            {{- if eq .Values.keycloak.hostname "localhost" }}
            {{- if .Values.debug }}
            - name: KC_LOG_LEVEL_ORG_KEYCLOAK
              value: debug
            {{- end }}
            - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
              value: "true"
            {{- end }}
            - name: KC_HOSTNAME
              value: "{{ .Values.keycloak.protocol }}://{{ .Values.keycloak.hostname }}"
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: adminUser
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: adminPassword
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: "jdbc:postgresql://keycloak-db:5432/{{ .Values.keycloak.dbName }}"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: dbUsername
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: dbPassword
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /opt/keycloak/data/import/damap-realm.json
              name: damap-realm
              subPath: damap-realm.json
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - "ALL"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: keycloak-db
spec:
  selector:
    app: keycloak-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: keycloak-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      securityContext:
        {{- if .Values.openshift }}
        runAsNonRoot: true
        {{- end }}
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      {{- if .Values.keycloak.persistData }}
      volumes:
      - name: keycloak-db
        persistentVolumeClaim:
          claimName: keycloak-db
      {{- end }}
      containers:
        - name: keycloak-db
          image: postgres:16
          resources:
            requests:
              cpu: 10m
              memory: 512Mi
            limits:
              memory: 2G
              cpu: "0.25"
          {{- if .Values.keycloak.persistData }}
          volumeMounts:
            - name: keycloak-db
              mountPath: /var/lib/postgresql/data
          {{- end }}
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/keycloak-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: dbUsername
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: dbPassword
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: dbDatabase
          ports:
            - containerPort: 5432
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - /usr/bin/pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- if .Values.openshift }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - "ALL"
          {{- end }}
{{- end }}
