{{- if .Values.keycloak.deploy }}

{{- $kcPath := include "keycloakPath" . | trim }}

{{- if and .Values.openshift (not .Values.keycloak.customDomain) }}
{{- /*
OpenShift default domain (Route)
*/}}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
  {{- if eq .Values.keycloak.protocol "https" }}
  annotations:
    haproxy.router.openshift.io/hsts_header: "max-age=31536000;includeSubDomains;preload"
  {{- end }}
spec:
  host: {{ .Values.keycloak.hostname }}
  path: {{ $kcPath | quote }}
  to:
    name: keycloak
    weight: 100
    kind: Service
  {{- if eq .Values.keycloak.protocol "https" }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  {{- end }}

{{- else }}
{{- /*
Vanilla K8s or OpenShift custom domain
*/}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: "{{ .Release.Namespace }}"
  {{- if and (eq .Values.keycloak.protocol "https") (.Values.keycloak.tlsClusterIssuer) }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.keycloak.tlsClusterIssuer }}
  {{- end }}
spec:
  {{- if .Values.keycloak.ingressClass }}
  ingressClassName: {{ .Values.keycloak.ingressClass }}
  {{- end }}
  {{- if eq .Values.keycloak.protocol "https" }}
  tls:
    - hosts:
        - {{ .Values.keycloak.hostname }}
      secretName: keycloak-tls
  {{- end }}
  rules:
    - host: {{ .Values.keycloak.hostname }}
      http:
        paths:
          - path: {{ default "/" $kcPath | quote }}
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
{{- end }}
{{- end }}
