include:
  - docker-compose.common.yaml

services:
  damap-be:
    # Since DAMAP containers are publicly available on GitHub packages one can
    # just pull the latest container image.
    image: ghcr.io/damap-org/damap-backend:next
    build:
      context: ../
    restart: unless-stopped
    environment:
      DAMAP_TITLE: "DAMAP Tool"
      DAMAP_DATASOURCE_URL: "jdbc:oracle:thin:@damap-db:1521/FREEPDB1"
      DAMAP_DATASOURCE_DIALECT: "org.hibernate.dialect.OracleDialect"
      DAMAP_DATASOURCE_DRIVER: "oracle.jdbc.driver.OracleDriver"
      DAMAP_DATASOURCE_DB_KIND: "oracle"
      DAMAP_DATASOURCE_USERNAME: "damap"
      DAMAP_DATASOURCE_PASSWORD: "pw4damap"
      QUARKUS_PROFILE: ${QUARKUS_PROFILE}
      DAMAP_MULTITENANT_CONFIG: /opt/damap/tenants.yaml
    volumes:
      - ./tenants.yaml://opt/damap/tenants.yaml:ro
    depends_on:
      - damap-db
      - keycloak
      - api-mock
      - fits-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health/live" ]
      interval: 30s
      timeout: 15s
      retries: 5

  damap-db:
    image: gvenzl/oracle-free:23-slim
    restart: unless-stopped
    environment:
      ORACLE_PASSWORD: pw4damap
      APP_USER: damap
      APP_USER_PASSWORD: pw4damap
    ports:
      - "8088:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: [ "CMD-SHELL", "healthcheck.sh" ]
      interval: 30s
      timeout: 15s
      retries: 5

volumes:
  oracle-data:
