services:
  damap-fe:
    # Since DAMAP containers are publicly available on GitHub packages one can
    # just pull the latest container image.
    image: ghcr.io/damap-org/damap-frontend:next
    pull_policy: always
    restart: unless-stopped

    # Assumed to be checked-out beside the 'damap-backend' repository.
    build:
      context: ../../damap-frontend
    depends_on:
      - damap-be

  proxy:
    # Since several components share the same ports and address, this docker
    # configuration needs a proxy to manage the connections between them,
    # as well as access from the outside.
    image: registry.hub.docker.com/library/nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8085:80"
    depends_on:
      - damap-fe
      - damap-be
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    pull_policy: always
    restart: unless-stopped
    command:
      - start
      - --http-enabled=true
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: ${KC_HOSTNAME:-http://localhost:8087}
      # Only needed if hostname is localhost
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: ${KC_HOSTNAME_BACKCHANNEL_DYNAMIC:-true}
    ports:
      - "8087:8080"
    volumes:
      - ./sample-damap-realm-export.json:/opt/keycloak/data/import/damap-realm-import.json
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:16
    pull_policy: always
    restart: unless-stopped
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
      DB_VENDOR: postgres

  api-mock:
    image: clue/json-server
    pull_policy: always
    restart: unless-stopped
    command: db.json --routes routes.json
    volumes:
      - ./api-mock/data/db.json:/data/db.json
      - ./api-mock/data/routes.json:/data/routes.json
    ports:
      - "8091:80"

  fits-service:
    image: islandora/fits:main
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8089:8080"

  gotenberg:
    image: gotenberg/gotenberg:8
    pull_policy: always
    restart: unless-stopped
    ports:
      - "3000:3000"
