include:
  - docker-compose.common.yaml

services:
  damap-be:
    # Since DAMAP containers are publicly available on GitHub packages one can
    # just pull the latest container image.
    image: ghcr.io/tuwien-csd/damap-backend:next
    build:
      context: ../
    restart: unless-stopped
    environment:
      DAMAP_TITLE: "DAMAP Tool"
      DAMAP_DATASOURCE_URL: "jdbc:postgresql://damap-db:5432/damap"
      DAMAP_DATASOURCE_DB_KIND: "postgresql"
      DAMAP_DATASOURCE_USERNAME: "damap"
      DAMAP_DATASOURCE_PASSWORD: "pw4damap"
    depends_on:
      - damap-db
      - keycloak
      - api-mock
      - fits-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health/live" ]
      interval: 30s
      timeout: 15s
      retries: 5

  damap-db:
    image: postgres:16
    pull_policy: always
    restart: unless-stopped
    environment:
      POSTGRES_USER: damap
      POSTGRES_PASSWORD: pw4damap
      POSTGRES_DB: damap
    ports:
      - "8088:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U damap -d damap'" ]
      interval: 30s
      timeout: 15s
      retries: 5

volumes:
  pg-data:
