# Example tenants used only when damap.multitenancy.tenants is empty.
tenant_1:
  title: Tenant 1 DAMAP Tool
  fields:
    ethical-report-enabled: false
  project-service: disabled
  elsevier-pure-description-classification: /dk/atira/pure/projectdescription
  elsevier-pure-contributor-role-classifications:
    - pure-role-uri: /dk/atira/pure/member
      contributor-role: PROJECT_MEMBER
  elsevier-pure-project-lead-role-classification: /dk/atira/pure/projectlead
  elsevier-pure-backend: http
  elsevier-pure-endpoint-url: "https://tenant1.example.com/ws/api/"
  elsevier-pure-api-key: "your API key here"
  elsevier-pure-projects-file: "file:///path/to/projects.json"
  elsevier-pure-persons-file: "file:///path/to/persons.json"
  person-services:
    - display-text: ORCID
      query-value: ORCID
      class-name: org.damap.base.integration.orcid.ORCIDPersonServiceImpl
tenant_2:
  title: Tenant 2 DAMAP Tool
  fields:
    ethical-report-enabled: false
  project-service: disabled
  elsevier-pure-description-classification: /dk/atira/pure/projectdescription
  elsevier-pure-contributor-role-classifications:
    - pure-role-uri: /dk/atira/pure/member
      contributor-role: PROJECT_MEMBER
  elsevier-pure-project-lead-role-classification: /dk/atira/pure/projectlead
  elsevier-pure-backend: http
  elsevier-pure-endpoint-url: "https://tenant2.example.com/ws/api/"
  elsevier-pure-api-key: "your API key here"
  elsevier-pure-projects-file: "file:///path/to/projects.json"
  elsevier-pure-persons-file: "file:///path/to/persons.json"
  person-services:
    - display-text: Pure
      query-value: PURE
      class-name: org.damap.base.integration.pure.PurePersonService
