apiVersion: v2
name: damap-chart
description: A tool to create machine-actionable data management plans.
type: application

version: 0.1.0-dev.8
appVersion: "5.0.0-dev.4"

kubeVersion: ">=1.25.0"

home: https://damap.org
sources:
  - https://github.com/damap-org/damap-backend
  - https://github.com/damap-org/damap-frontend

keywords:
  - damap
  - data-management
  - dmp
  - research
  - pure
  - keycloak
  - oidc
  - openid

maintainers:
  - name: DAMAP Team
    email: info@damap.org

icon: https://damap.org/logo.svg

annotations:
  artifacthub.io/prerelease: "true"
  artifacthub.io/changes: |
    - kind: changed
      description: Bump DAMAP backend version to 5.0.0-dev.4
    - kind: fixed
      description: Fix routing when keycloak is deployed on the same domain as the frontend.
