# Helm chart publishing workflow
# - Publishes OCI Helm charts from the `main` branch
# - Triggered only when `chart/Chart.yaml` changes
# - Chart versions must be bumped manually in Chart.yaml

name: Release Helm Chart

env:
  REGISTRY: ghcr.io

on:
  push:
    branches:
      - main
    paths:
      - "chart/Chart.yaml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  helm-publish:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Log in to GHR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          helm registry login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Compute Chart metadata
        id: chart
        run: |
          name=$(grep '^name:' chart/Chart.yaml | awk '{print $2}')
          version=$(grep '^version:' chart/Chart.yaml | awk '{print $2}')

          echo "name=$name" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Helm Lint
        run: helm lint chart/

      - name: Package Helm chart
        run: helm package chart/ --destination ./

      - name: Push Helm Chart to GHR
        run: |
          helm push ${{ steps.chart.outputs.name }}-${{ steps.chart.outputs.version }}.tgz \
          oci://${{ env.REGISTRY }}/${{ github.repository_owner }}
